pipeline {
    agent any

    tools {
        maven 'Maven3'
    }

    environment {
        DOCKERHUB_CREDENTIALS_ID = 'Docker_hub'
        DOCKERHUB_REPO = 'alekspka/shoppingcart'
        DOCKER_IMAGE_TAG = 'latest'
    }
    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/alekspka/SEP-2'
            }
        }

        stage('Build and Test') {
            steps {
                dir('Week1') {
                    bat 'where java'
                    bat 'java -version'
                    bat 'mvn -version'
                    bat 'mvn clean verify'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit 'Week1/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                jacoco(
                    execPattern: 'Week1/target/jacoco.exec',
                    classPattern: 'Week1/target/classes',
                    sourcePattern: 'Week1/src/main/java',
                    inclusionPattern: '**/*.class'
                )
            }
        }

        stage('SonarQube Analysis') {
            steps {
                dir('Week1') {
                    withSonarQubeEnv('SonarQubeServer') {
                        withCredentials([string(credentialsId: 'SONAR', variable: 'SONAR_TOKEN')]) {
                            bat 'mvn org.sonarsource.scanner.maven:sonar-maven-plugin:4.0.0.4121:sonar -Dsonar.projectKey=Shoppingcart -Dsonar.projectName=Shoppingcart -Dsonar.token=%SONAR_TOKEN%'
                        }
                    }
                }
            }
        }


        stage('Build Docker Image') {
            steps {
                dir('Week1') {
                    bat 'docker build -t %DOCKERHUB_REPO%:%DOCKER_IMAGE_TAG% .'
                }
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                withCredentials([usernamePassword(credentialsId: DOCKERHUB_CREDENTIALS_ID, usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                    bat '''
                    echo %DOCKERHUB_PASS%| docker login -u %DOCKERHUB_USER% --password-stdin
                    docker push %DOCKERHUB_REPO%:%DOCKER_IMAGE_TAG%
                    docker logout
                    '''
                }
            }
        }
    }

    post {
        always {
            cleanWs()
        }
        failure {
            echo 'Pipeline failed.'
        }
    }
}