pipeline {
    agent any

    environment {
        // Define Docker Hub credentials ID
        DOCKERHUB_CREDENTIALS_ID = 'Docker_hub'
        // Define Docker Hub repository name
        DOCKERHUB_REPO = 'alekspka/shoppingcart'
        // Define Docker image tag
        DOCKER_IMAGE_TAG = 'latest'
    }

    stages {
        stage('Checkout') {
            steps {
                git branch: 'main', url: 'https://github.com/alekspka/SEP-2'
            }
        }

        stage('Build') {
            steps {
                dir('Week1') {
                    bat 'mvn clean install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('Week1') {
                    bat 'mvn test'
                }
            }
        }

        stage('Code Coverage') {
            steps {
                dir('Week1') {
                    bat 'mvn org.jacoco:jacoco-maven-plugin:0.8.13:report'
                }
            }
        }

        stage('Publish Test Results') {
            steps {
                junit '**/target/surefire-reports/*.xml'
            }
        }

        stage('Publish Coverage Report') {
            steps {
                jacoco()
            }
        }

        stage('Build Docker Image') {
            steps {
                // Build Docker image from Week1 directory
                bat 'docker build -t %DOCKERHUB_REPO%:%DOCKER_IMAGE_TAG% Week1'
            }
        }

        stage('Push Docker Image to Docker Hub') {
            steps {
                // Login, push and logout using Jenkins credentials binding
                withCredentials([usernamePassword(credentialsId: DOCKERHUB_CREDENTIALS_ID, usernameVariable: 'DOCKERHUB_USER', passwordVariable: 'DOCKERHUB_PASS')]) {
                    bat '''
                    echo %DOCKERHUB_PASS%| docker login -u %DOCKERHUB_USER% --password-stdin
                    docker push %DOCKERHUB_REPO%:%DOCKER_IMAGE_TAG%
                    docker logout
                    '''
                }
            }
        }
    }
}