sonar.projectKey=Shoppingcart
sonar.projectName=Shoppingcart
sonar.projectVersion=1.0
sonar.sources=src
sonar.java.binaries=target/classes
sonar.coverage.jacoco.xmlReportPaths=target/site/jacoco/jacoco.xml
sonar.coverage.exclusions=src/main/java/org/example/ShoppingCartGUI.java,src/main/java/org/example/DatabaseConnection.java,src/main/java/org/example/CartService.java,src/main/java/org/example/LocalizationService.java
sonar.host.url=http://localhost:9000
